"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
gamepad features are by default exposed.

#### Granted Permissions

It allows access to all gamepads.

"""

permissions = [
  "allow-execute",
  "allow-get-logging",
  "allow-set-logging",
]