"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
gampead features are by default exposed.

#### Granted Permissions

It allows acccess to all gamepads.

"""

permissions = [
  "allow-execute"
]